# ~/.config/alacritty/alacritty.toml
# /c/Users/mrvon/AppData/Roaming/alacritty/alacritty.toml
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
[window]
dimensions = {columns = 0, lines = 0}
opacity = 1.0
padding.x = 0
padding.y = 0
decorations = "None"
startup_mode = "Maximized"

[env]
# TERM = "tmux-256color"

[font]
size = 13
offset = {x = 0, y = 0}
glyph_offset = {x = 0, y = 0}
normal = { family = "Monaco Nerd Font Mono", style = "Regular" }
# buggy here
# bold = { style = "Bold" }
italic = { style = "Bold" }
# bold_italic = { style = "Bold Italic" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", action = "PasteSelection" },
]

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[scrolling]
history = 5000
multiplier = 3

# [terminal]
# [terminal.shell]
# program = 'C:\Program Files\Git\bin\bash.exe'
# args = [ "--login", ]

[colors]
draw_bold_text_with_bright_colors = true

[general]
import = [
  "~/.config/alacritty/themes/themes/authur.toml"
]
