# ~/.config/alacritty/alacritty.toml
# /c/Users/mrvon/AppData/Roaming/alacritty/alacritty.toml
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
[window]
dimensions = {columns = 0, lines = 0}
opacity = 0.9
padding.x = 0
padding.y = 0
decorations = "None"
startup_mode = "Maximized"

[env]
# TERM = "tmux-256color"

[font]
size = 14
offset = {x = 0, y = 0}
glyph_offset = {x = 0, y = 0}

[font.normal]
family = "Monaco Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Monaco Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Monaco Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "Monaco Nerd Font Mono"
style = "Bold"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", action = "PasteSelection" },
]

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[scrolling]
history = 5000
multiplier = 3

[general]
import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
    # "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

# [terminal]
# [terminal.shell]
# program = 'C:\Program Files\Git\bin\bash.exe'
# args = [ "--login", ]
